In [4]:
import numpy as np
import matplotlib.pyplot as plt

<i>Using the convolve function was not an original idea - I would like to thank Stackoverflow for this.</i>

In [25]:
width = 7

array = np.array([0,1,2,3,4,5,6,7,8])
print(np.convolve(array, np.ones(width), 'valid')/width)
print(array[int((width-1)/2):-int((width-1)/2)])

[3. 4. 5.]
[3 4 5]


In [1]:
int(0.1)

0

In [2]:
int(0.8)


0

In [9]:
t = np.linspace(1,20,21)
t
# t += 1
t

array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
        9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
       18.1 , 19.05, 20.  ])